apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres:alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-db-secret
              key: postgres-root-password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-db-secret
              key: postgres-root-user
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-db-configmap
              key: postgres-database
        resources:
          requests:
            memory: "2G"
            cpu: 2
            hugepages-2Mi: "261Mi"
          limits:
            memory: "3.2G"
            cpu: 4
            hugepages-2Mi: "261Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432